library(shiny)
library(grid)
library(lattice)
library(ggthemes)
library(shinythemes)
library(ggplot2)
library(plyr)
library(pequod)
#library(plot3D)
#library(plot3Drgl)
library(psych)
library(car)
#library(rgl)
#library(broom)
#library(knitr)

#library(rmarkdown)
#library(rockchalk)

